 [package]
 name = "pattern_matching"
 version = "0.1.0"
 edition = "2021"
 
 [dependencies]
 clap = { version = "4.5.4", features = ["derive"] }
 glob = "0.3.1"
 regex = "1.10.4"
 serde = { version = "1.0.203", features = ["derive"] }
 serde_json = "1.0.117"
 toml = "0.8.12"
